import 'dotenv/config';
import { writeFileSync, mkdirSync } from 'fs';

const API_KEY = process.env.VITE_OPENTRIPMAP_API_KEY;

const TRIP_STOPS = {
  'eastern-circuit': [
    { name: 'Toronto',               coords: [43.6532, -79.3832] },
    { name: 'Kingston',              coords: [44.2312, -76.4860] },
    { name: 'Ottawa',                coords: [45.4215, -75.6972] },
    { name: 'Montréal',              coords: [45.5017, -73.5673] },
    { name: 'Prince Edward County',  coords: [44.0082, -77.1386] },
  ],
  'new-brunswick-fundy': [
    { name: 'Toronto',                    coords: [43.6532, -79.3832] },
    { name: 'Quebec City, QC',            coords: [46.8139, -71.2080] },
    { name: 'Rimouski, QC',               coords: [48.4281, -68.5220] },
    { name: 'Fredericton, NB',            coords: [45.9636, -66.6431] },
    { name: 'Alma / Fundy National Park', coords: [45.6002, -64.9474] },
    { name: 'Hopewell Rocks',             coords: [45.8236, -64.5751] },
    { name: 'St. Andrews by-the-Sea',     coords: [45.0738, -67.0531] },
  ],
};

function mapCategory(kinds) {
  if (!kinds) return 'Attraction';
  if (kinds.includes('natural'))       return 'Nature';
  if (kinds.includes('historic'))      return 'Historic site';
  if (kinds.includes('museums'))       return 'Museum';
  if (kinds.includes('architecture'))  return 'Architecture';
  if (kinds.includes('cultural'))      return 'Cultural site';
  if (kinds.includes('parks'))         return 'Park';
  if (kinds.includes('religion'))      return 'Religious site';
  if (kinds.includes('amusements'))    return 'Amusement';
  return 'Attraction';
}

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function fetchCity(name, lat, lon) {
  const url = `https://api.opentripmap.com/0.1/en/places/radius?radius=5000&lon=${lon}&lat=${lat}&kinds=interesting_places&rate=2&format=json&limit=15&apikey=${API_KEY}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${name}`);
  const data = await res.json();

  const seen = new Set();
  return (Array.isArray(data) ? data : [])
    .filter(item => {
      if (!item.name || item.name.trim() === '') return false;
      const key = item.name.toLowerCase().trim();
      if (seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map(item => ({
      xid: item.xid,
      name: item.name.trim(),
      category: mapCategory(item.kinds),
      coords: [item.point.lat, item.point.lon],
      url: `https://opentripmap.com/en/card/${item.xid}`,
      dist: Math.round(item.dist),
    }));
}

async function main() {
  if (!API_KEY) {
    console.error('Missing VITE_OPENTRIPMAP_API_KEY in .env');
    process.exit(1);
  }

  const result = {};

  for (const [tripId, stops] of Object.entries(TRIP_STOPS)) {
    result[tripId] = {};
    for (const stop of stops) {
      const [lat, lon] = stop.coords;
      console.log(`Fetching: ${stop.name} (${tripId})...`);
      try {
        result[tripId][stop.name] = await fetchCity(stop.name, lat, lon);
        console.log(`  ✓ ${result[tripId][stop.name].length} attractions`);
      } catch (err) {
        console.error(`  ✗ ${err.message}`);
        result[tripId][stop.name] = [];
      }
      await sleep(1100);
    }
  }

  mkdirSync('src/data', { recursive: true });
  writeFileSync(
    'src/data/openTripMapCityAttractions.js',
    `// Generated by scripts/fetchCityAttractions.mjs — do not edit manually.\n// Regenerate: node scripts/fetchCityAttractions.mjs\n\nexport const OPENTRIPMAP_CITY_ATTRACTIONS = ${JSON.stringify(result, null, 2)};\n`,
    'utf8'
  );
  console.log('\n✓ Written to src/data/openTripMapCityAttractions.js');
}

main();
